### ISSUE TITLE
Supported MM Versions

### ISSUE THREAD

**Issue by belfhi** [mattermost/mattermost-helm#139]
What are the supported versions of Mattermost in this Helm Chart?
The default is a 5.13 but this is already outdated.
Can I use the most recent Docker Image of MM?

**Comment by cyboman32** [comment]
Guys, we need an upgrade! iOS client requires 5.19+.

**Comment by belfhi** [comment]
So I switched to the 5.22 docker image and it works but mm now runs under uid 2000 so /data and /plugins that were used by previous versions need to be chown'd to the new uid:gid that mm now uses.

**Comment by etlfg** [comment]
Thanks @cyboman32 for the quick but working way. I was wondering about adding a securityContext section in the deployment template of this chart depending on the selected version. 

Something like (naive way):
```
{{ if gt (semver .Values.image.tag) (semver "5.14") }}
      securityContext:
        fsGroup: 2000
...
```
That would need to take into account the data/plugin enabling because we don't have the /data and /plugins volumes if they're not enabled.

I can do this. Would you be interested about a PR with this in mind ?

**Comment by MattInternet** [comment]
Is there a reason the version listed in values.yaml is still `5.29.0`? A bunch of the clients want 5.31+ now...

**Comment by belfhi** [comment]
Well currently there is a blocking issue #203 which prevents you from using MM v5.30+. I'm considering moving to the Operator since that seems to be better supported.

**Comment by cpanato** [comment]
will be fixed in this PR for MM-TE: https://github.com/mattermost/mattermost-helm/pull/225

closing this issue
