### ISSUE TITLE
Unable to upload media due to permissions error, fixed by restarting

### ISSUE THREAD

**Issue by MattInternet** [mattermost/mattermost-helm#155]
I have a very simple deployment with nothing related to volumes altered in my values.yaml

After updating to something less than 5.24.0 I had an issue where anything that required uploading media errored with:
`Encountered an error creating the directory for the new file.`

I don't remember the version but it was only a couple days ago.

After looking in the logs it was getting a permission error. I checked the permissions on /mattermost in the pod and it had the permissions correctly set to `mattermost`. I also checked that the drive wasnt full.

Idk what happened but after upgrading to 5.24.0 it works again. I think it might've just been the restart that did it.

**Comment by suda** [comment]
I have the same problem. I believe the root cause is that the volumes are owned by `root` but the Mattermost container is running as `mattermost`:
![Screenshot from 2020-06-27 19-31-09](https://user-images.githubusercontent.com/25722/85928383-d96e6d80-b8ac-11ea-8ccc-088cbf0947d0.png)

This might need an [init container](https://stackoverflow.com/a/51195446/83055) to fix the permissions. I ended up opening a shell in the pod and changing the owner of the mounted volumes.

**Comment by geonux** [comment]
We have the same problem. The init container seems to be a solution. In the meantime, @suda could you give me the workaround to change the directories' rights. In the POD console, I'm logged with the `mattermost` account, so I don't have the rights to change the owner of the directories.

**Comment by geonux** [comment]
I have found a workaround using the kubectl ssh plugin (from https://github.com/jordanwilson230/kubectl-plugins) to be `root` on the mattermost POD and modify the directory owner.

**Comment by suda** [comment]
Yep, that's exactly what I used!

**Comment by ohemelaar** [comment]
For me restarting didn't fix the problem.

Also, I wasn't able to use a manual `docker exec` from a node or the `kubectl ssh` plugin because our container runtime is containerd and not docker.

`kubectl` has not yet stabilized their `debug` command using ephemeral containers so that can't be used in production too ([see this comment](https://github.com/kubernetes/kubernetes/issues/30656#issuecomment-625626368)).

Containerd's `ctr` [CLI tool is not stable yet](https://github.com/containerd/containerd/blob/3560a453e4435a8d0b9382c5e631c68644dd0671/RELEASES.md#public-api-stability) and documentation is very sparse. I couldn't find a way to use it to run a shell as root in the mattermost pod.

Because of all of this, the way I ended up fixing the problem was the manual way:
- Check to user if for mattermost in the pod using `id`. For me it was `2000`
- Scale the mattermost deployment to 0
- Attach mattermost's volumes (data and plugins) to a VM and mount them
- Run `chmod -R 2000:2000 <mount path>` for both mounts
- Unmount the volumes, detach them from the VM, and scale mattermost back up

**Comment by cpanato** [comment]
will close this due inactivity 
feel free to reopen or open a new issue if this still an issue
